{
 "title": "Satellite Summary",
 "description": "Satellite Summary Screen",
 "tags": [
  "linux",
  "spacewalk"
 ],
 "time": { "from": "now-6h", "to": "now-30s" },
 "refresh": "1m",
 "panels": [
  { "title": "Satellite Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registered Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT (*)\nFROM public.hosts"
    }
   ]
  },
  {
   "title": "Servers Requiring Updates",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(host_id)\r\nFROM katello_content_facets "
    }
   ]
  },
  {
   "title": "Total Distinct Bugfix Errata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT COUNT(DISTINCT(errata_id)) AS NAME\r\nFROM katello_errata\r\nWHERE errata_type = 'bugfix'"
    }
   ]
  },
  {
   "title": "Total Distinct Outstanding Errata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select count(distinct(errata_id)) from katello_errata;  "
    }
   ]
  },
  {
   "title": "Total Distinct Security Errata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT COUNT(DISTINCT(errata_id)) AS NAME\r\nFROM katello_errata\r\nWHERE errata_type = 'security'"
    }
   ]
  },
  {
   "title": "Total Distinct Critical Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT COUNT(severity)  \r\nFROM katello_errata \r\nWHERE severity = 'Critical'\r\n"
    }
   ]
  },
  {
   "title": "Packages Applied < 30 days",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT COUNT(id)\r\nFROM katello_content_view_histories \r\nWHERE status = 'successful'\r\nAND updated_at > CURRENT_DATE - INTERVAL '30' DAY;\r\n"
    }
   ]
  },
  {
   "title": "Katello Pakages Update Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT now() AS time,COUNT(errata_type), errata_type \r\nFROM katello_errata \r\nGROUP by errata_type\r\n"
    }
   ]
  },
  {
   "title": "Katello Pakages Update Severity",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT now() AS TIME,COUNT(severity), severity \r\nFROM katello_errata \r\nGROUP by severity"
    }
   ]
  },
  {
   "title": "Updates Requires",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT SUM(katello_content_facets.installable_security_errata_count+\r\nkatello_content_facets.installable_bugfix_errata_count+\r\nkatello_content_facets.installable_enhancement_errata_count+\r\nkatello_content_facets.applicable_rpm_count+\r\nkatello_content_facets.upgradable_rpm_count\r\n) AS Updates,\r\nhosts.NAME AS fqdn\r\nFROM katello_content_facets, hosts\r\nWHERE hosts.id = katello_content_facets.host_id\r\nGROUP by NAME\r\n"
    }
   ]
  },
  {
   "title": "Katello Errata",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT errata_id AS Errata, errata_type AS \"Tipe Errata\", to_char(issued,'MM/DD/YYYY') as ISSUED , title as Title, solution as Solution\r\nFROM katello_errata"
    }
   ]
  },
  {
   "title": "Updates Requires per Errata",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT hosts.NAME AS NAME, \r\nkatello_content_facets.installable_security_errata_count,\r\nkatello_content_facets.installable_bugfix_errata_count,\r\nkatello_content_facets.installable_enhancement_errata_count,\r\nkatello_content_facets.applicable_rpm_count,\r\nkatello_content_facets.upgradable_rpm_count\r\nFROM katello_content_facets, hosts\r\nWHERE hosts.id = katello_content_facets.host_id\r\n"
    }
   ]
  }
 ]
}